variable "account_id" {}
variable "region" {}
variable "project" {}
variable "env" {}
variable "vpc_id" {}
variable "subned_public_1a_id" {}
variable "subned_public_1c_id" {}
variable "web_container_name" {}
variable "ecs_sg_id" {}
variable "ecs_task_execution_role_arn" {}
variable "cloudwatch_log_group_for_ecs" {}
variable "target_group_arn" {}